apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/yeobi01/argocd-helm.git
    path: ingress-nginx-4.12.1/
    targetRevision: HEAD
    helm:
      valueFiles:
        - my-values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
